[phases.setup]
python.version = "3.11"
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn -w 2 -k gevent --timeout 3600 -b 0.0.0.0:$PORT server:app"
